### ISSUE TITLE
Save Lock

### ISSUE THREAD

**Issue by raphoux69** [GenesisFR/TheWitcher2SavelockBypasser#1]
Sorry to write you about an old work.
But i quite don't understand how you're supposed to remove the save lock.
I don't really understand the explanation.
Installing the program worked. The question remains is the usage. Because if it's intended just to use a button to unlock saves, it doesn't work.

**Comment by GenesisFR** [comment]
If I remember correctly, the game writes a key in registry to keep track whether you died or not in a given playthrough.

Initially, the key has a length of 25 bytes (these are basically 25 numbers) for your first playthrough, and every time you start a new playthrough, the size increases by 5 bytes. The byte that gets changed when you die is the second to latest byte corresponding to the current playthrough, so if for instance you die in your 3rd playthrough and you had 4 playthroughs in progress, byte n°34 will change even though the key has a length of 40 bytes.

The caveat is that because I wasn't able to find the logic related to how the value of that byte gets changed, I just started 5 playthroughs and died in all of them just to see what were the new values, so I obviously wasn't going to do it manually for 1000 playthroughs.

Pressing the Unlock button should unlock ALL playthroughs. If it doesn't work, it probably means you had more than 5 playthroughs. You should have gotten a warning about it when launching the program and you can double check if the registry key contains more than 45 bytes (therefore more than 5 playthroughs) by clicking the "Open in Regedit" button.

This is where I find out how many playthroughs you have: https://github.com/GenesisFR/TheWitcher2SavelockBypasser/blob/master/TheWitcher2SavelockBypasser/TheWitcher2SavelockBypasserForm.cs#L106

And this is where I unlock all of them: https://github.com/GenesisFR/TheWitcher2SavelockBypasser/blob/master/TheWitcher2SavelockBypasser/TheWitcher2SavelockBypasserForm.cs#L234

You could also try running the program as admin, maybe there's a permission issue that prevents it from accessing the registry when reading the key and clicking the Unlock button.

Let me know if that helped.

**Comment by raphoux69** [comment]
I initially thought that i had too many playthroughs. I justed wanted to
know if deleting saves would change things, since i did many runs to test
many builds.

Now coming back to the tool.
The first thing i don't understand is that i have no open regedit button,
which is not normal, since i have a register editor.
So i tried to run the file you showcased in the first link and i had a
syntax error at first on line 264 because of $ that i simply removed. I
think it's a plain syntax error. But then i had such type of errors, where
he cannot find  'RegistryChangeMonitor' +  'RegistryChangeEventArgs' and i
don't know why. The third error is just linked to the second in the error i
sent you.


TheWitcher2SavelockBypasserForm.cs(13,17): error CS0246: Le type ou le nom
d'espace de noms 'RegistryChangeMonitor' est introuvable (une directive
using ou une référence d'assembly est-elle manquante ?)
TheWitcher2SavelockBypasserForm.cs(82,62): error CS0246: Le type ou le nom
d'espace de noms 'RegistryChangeEventArgs' est introuvable (une directive
using ou une référence d'assembly est-elle manquante ?)
TheWitcher2SavelockBypasserForm.cs(82,86): error CS1750: Une valeur de type
'<null>' ne peut pas être utilisée comme paramètre par défaut car il
n'existe pas de conversions standard de type 'RegistryChangeEventArgs'

  But your first assumption makes sens, just wanted to check if i had less
that 5 playthroughs on this difficulty mode. I ran the programm but it just
said success and still didn't work.

**Comment by GenesisFR** [comment]
I'm gonna look into it tomorrow. It seems like I forgot to compile the latest version (though the functionality stays unchanged besides the +5 playthroughs warning that was added).

**Comment by GenesisFR** [comment]
> So i tried to run the file you showcased in the first link and i had a syntax error at first on line 264 because of $ that i simply removed. I think it's a plain syntax error. But then i had such type of errors, where he cannot find 'RegistryChangeMonitor' + 'RegistryChangeEventArgs' and i don't know why. The third error is just linked to the second in the error i sent you.

You're not supposed to compile that file alone but open the project's solution instead.

I released a new version with the latest changes, let me know if anything new comes up: https://github.com/GenesisFR/TheWitcher2SavelockBypasser/releases/tag/v1.1

**Comment by raphoux69** [comment]
Oh i didn't knew. So this explains why.
I'm currently away, i will keep in touch when i come back when i test this,
so do not worry if don't reply for a while.

**Comment by GenesisFR** [comment]
Alright.

**Comment by raphoux69** [comment]
So I tested your new addition.
You get the warning now if you have more playthroughs and you can read your
key in regedit too.
The unlock button will still say it's successful even if you've more than 5
playthroughs though.
Another thing, even if you delete saves, playthroughs are still counted
separately it seems. So deleting saves of previous playthroughs won't
change a thing.
The number of saves isn't the number of playthroughs.

**Comment by GenesisFR** [comment]
The number of saves has nothing to do with how many playthroughs you've started. What's in the registry doesn't lie, if the key is over 45 bytes long but you only have one save, it means you've started more than 5 playthroughs. If you're gonna delete all saves, you gotta delete the key in registry too otherwise it creates a mismatch for the tool.

The unlock button says successful because it unlocks the first 5 playthroughs regardless of how many you had.

If you unlocked everything and your save is still locked because you had more than 5 playthroughs, then you're out of luck with this tool.

Your only salvation is to increase (or maybe decrease, I don't remember) the byte in the registry corresponding to your playthrough by 1 (in decimal). For the first playthrough it's the 9th byte, second 14th, third 19th, etc.

**Comment by GenesisFR** [comment]
Any news on this? Were you able to revive your character?

**Comment by raphoux69** [comment]
Well, i tried, but since i had started many playthroughs just to test
things. It just go out of hand and thus i just recreated a playthrough.
I can see that in theory decreasing the byte might work, but when you go
above a few saves it seems tedious.
Furthermore, i was unsure how the byte system worked in the sense that even
if i reduce the byte number of the playthrough, the key would still be
longer.
And deleting those, in my opinion, would have been ill advised.

Was worth a try, but oh well.

**Comment by GenesisFR** [comment]
Well, you can see why I limited myself to only 5 playthroughs then, it was tedious for me as well and I couldn't find a way to automate it since numbers seemed random.

Bytes must not be deleted, just a specific one matching your playthrough decreased (or increased, I don't remember, it's been too long and I'm not gonna reinstall the game just to check) by one.

I'm gonna close this since you ended up restarting the game.
